server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://192.168.2.246:3306/cq_angel?noAccessToProcedureBodies=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
